version: 1.0.{build}

branches:
  # whitelist
  only:
    - sam-cli-release

image:
  - macos-bigsur

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
for:
  -
    matrix:
      only:
        - image: macos-bigsur

    before_build:
      - echo "Mac don't need any before_build steps."

# Building bottles shell script.
build_script:
  - brew tap aws/tap
  - sudo bash ./replace-local-tap.sh
  - ./build-formula.sh -f Formula/aws-sam-cli.rb -u

artifacts:
  - path: "build/*.bottle.tar.gz"
