# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2-spot-interrupter" do
  name "ec2-spot-interrupter"
  desc "A simple CLI tool that triggers Amazon EC2 Spot Interruption Notifications and Rebalance Recommendations."
  homepage "https://github.com/aws/amazon-ec2-spot-interrupter"
  version "0.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2-spot-interrupter"

  on_macos do
    on_intel do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_darwin_amd64.tar.gz"
      sha256 "de7537fab15a9bf7ef339a8eca279796a5874046a70f7394975ae82ba80a7058"
    end
    on_arm do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_darwin_arm64.tar.gz"
      sha256 "581b6f03bfe0066de189f7ce294b8bb503bb44f0a405740970ab25d903f34e7a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_linux_amd64.tar.gz"
      sha256 "05bf53cdabe89a0149c1ceb3f456ee9f6706fdf5c9789dcaa0ce3d839b254d0b"
    end
    on_arm do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_linux_arm64.tar.gz"
      sha256 "2465c653facb2d508a5fae7582acc5b7ffd3276acb4ca62532cd7053595b25c5"
    end
  end

  caveats do
    "ec2-spot-interrupter --interactive"
  end

  # No zap stanza required
end
