# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2-spot-interrupter" do
  name "ec2-spot-interrupter"
  desc "A simple CLI tool that triggers Amazon EC2 Spot Interruption Notifications and Rebalance Recommendations."
  homepage "https://github.com/aws/amazon-ec2-spot-interrupter"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2-spot-interrupter"

  on_macos do
    on_intel do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_darwin_amd64.tar.gz"
      sha256 "867d1ea0c4e64638e54d9b4b91809f689d7a0378b0e3743c87a0a483c7697b98"
    end
    on_arm do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_darwin_arm64.tar.gz"
      sha256 "d42f4e93d25d1bfabe918c4e4ff0478422f702ce6e8cda74a7acaeb33204a8ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_linux_amd64.tar.gz"
      sha256 "7a504350e186d4803899c2dfd3cb0a25cd2bd2ec48cacfee3b6791c76bbc6e1d"
    end
    on_arm do
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v#{version}/ec2-spot-interrupter_linux_arm64.tar.gz"
      sha256 "542fed49faf445bce7b5a40822f7ecdf6ee38faf8af9e37767b4831e124595d0"
    end
  end

  caveats do
    "ec2-spot-interrupter --interactive"
  end

  # No zap stanza required
end
