# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodecatalystRunnerCli < Formula
  desc "CLI to run CodeCatalyst workflows locally 🧰"
  homepage "https://github.com/aws/codecatalyst-runner-cli"
  version "0.4.16"
  license "Apache-2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aws/codecatalyst-runner-cli/releases/download/0.4.16/ccr_Darwin_x86_64.tar.gz"
      sha256 "13832e63f2df915a211763126b4ac3a1381c57e7a19c9e0795f1a57197fa9f40"

      def install
        bin.install "ccr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aws/codecatalyst-runner-cli/releases/download/0.4.16/ccr_Darwin_arm64.tar.gz"
      sha256 "bed4c5a26b69942fc540b71cd4440d94935f097d6442faf91920f89ab3dcc42e"

      def install
        bin.install "ccr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aws/codecatalyst-runner-cli/releases/download/0.4.16/ccr_Linux_arm64.tar.gz"
      sha256 "3fac7de6402ca6ea86c061565688c8b60ac31d180477e548ae26a50ab8c90e25"

      def install
        bin.install "ccr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aws/codecatalyst-runner-cli/releases/download/0.4.16/ccr_Linux_x86_64.tar.gz"
      sha256 "c2d9e178a6e00e173dab0afd96f7d05c4b4c956c488040dfd6e09fd513e4359d"

      def install
        bin.install "ccr"
      end
    end
  end

  test do
    system "#{bin}/ccr --version"
  end
end
