# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2SpotInterrupter < Formula
  desc "A simple CLI tool that triggers Amazon EC2 Spot Interruption Notifications and Rebalance Recommendations."
  homepage "https://github.com/aws/amazon-ec2-spot-interrupter"
  version "0.0.8"
  license "Apache-2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.8/ec2-spot-interrupter_0.0.8_Darwin_arm64.tar.gz"
      sha256 "375905beefa29b8734a1e7e35ec055479aa640bb59b25361c218734877a7b070"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.8/ec2-spot-interrupter_0.0.8_Darwin_amd64.tar.gz"
      sha256 "be110287538a532df625a9865bbba0d50cd1bb9ee67e70965de3e3fc34e2a31f"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.8/ec2-spot-interrupter_0.0.8_Linux_armv6.tar.gz"
      sha256 "eae2db112b86f17655a036deb56c2c18eba653d41853cc5b66bde453fcbd7262"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.8/ec2-spot-interrupter_0.0.8_Linux_amd64.tar.gz"
      sha256 "d5dec8e5c7b281eddd83c72e591d5d0f3a9dd372a032ead9cad9a3785e4f9a44"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
  end

  def caveats; <<~EOS
    ec2-spot-interrupter --interactive
  EOS
  end

  test do
    system "#{bin}/program --version"
  end
end