# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2SpotInterrupter < Formula
  desc "A simple CLI tool that triggers Amazon EC2 Spot Interruption Notifications and Rebalance Recommendations."
  homepage "https://github.com/aws/amazon-ec2-spot-interrupter"
  version "0.0.10"
  license "Apache-2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.10/ec2-spot-interrupter_0.0.10_Darwin_arm64.tar.gz"
      sha256 "fc1baf8fcdfef6f640b99a524a60c6fb47b7f249d0827ea6f80ca04acdf5740b"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.10/ec2-spot-interrupter_0.0.10_Darwin_amd64.tar.gz"
      sha256 "a2d0e614242c9e8281b3077d8b6c84dd2610aa447abb3ce95e2cbfe350d88f2d"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.10/ec2-spot-interrupter_0.0.10_Linux_armv6.tar.gz"
      sha256 "83b9faadc6c3990d4e775ebde4134d62bb6b6fd4909e49d3f287f738fe778d2a"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aws/amazon-ec2-spot-interrupter/releases/download/v0.0.10/ec2-spot-interrupter_0.0.10_Linux_amd64.tar.gz"
      sha256 "b0cda18f79aace89424c8963a6d39107c9168535a9b8bd0424fb2bb57d82b531"

      def install
        bin.install "ec2-spot-interrupter"
      end
    end
  end

  def caveats
    <<~EOS
      ec2-spot-interrupter --interactive
    EOS
  end

  test do
    system "#{bin}/program --version"
  end
end
