# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eksdemo < Formula
  desc "The easy button for learning, testing and demoing Amazon EKS"
  homepage "https://github.com/awslabs/eksdemo"
  version "0.11.0"
  license "MIT-0"

  depends_on "weaveworks/tap/eksctl"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.11.0/eksdemo_Darwin_arm64.tar.gz"
      sha256 "45af4e8555d22abc7e075e23b13e042dd0e47434839a7b48086c27038cc82213"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.11.0/eksdemo_Darwin_x86_64.tar.gz"
      sha256 "d18696a93f99e2ddd4f9fa84c4f0c4fdb21fb9572a78326dbc08943166a122dd"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.11.0/eksdemo_Linux_arm64.tar.gz"
      sha256 "e65b8d4170f410fdc9c4183d3f8b7855df773146fbbe79b3d8eea0454e480259"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.11.0/eksdemo_Linux_x86_64.tar.gz"
      sha256 "b2c7ab5348cd7b5e57c55752cda8c32c6bea0e2a671180c2d18ee4f377986517"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end
end
