# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eksdemo < Formula
  desc "The easy button for learning, testing and demoing Amazon EKS"
  homepage "https://github.com/awslabs/eksdemo"
  version "0.12.0"
  license "MIT-0"

  depends_on "weaveworks/tap/eksctl"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.12.0/eksdemo_Darwin_arm64.tar.gz"
      sha256 "8ab671f791f982033d3c0189668e62d77a10d112ab8a77c116032040abc1d481"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.12.0/eksdemo_Darwin_x86_64.tar.gz"
      sha256 "5f4f65568c7c840dc830bb52421ba64b5eeaae5bc0466e40d5b3c1415b085107"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.12.0/eksdemo_Linux_arm64.tar.gz"
      sha256 "9fe8d65708da6efc2cdaa3eeee59925841abaf3992248d03cc0efc67d82eeafa"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/awslabs/eksdemo/releases/download/v0.12.0/eksdemo_Linux_x86_64.tar.gz"
      sha256 "e73109d1eb641e478866fa8c08890a9f498252712c5cd23e2ade2d6fd6b3006f"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end
end
