# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eksdemo < Formula
  desc "The easy button for learning, testing and demoing Amazon EKS"
  homepage "https://github.com/awslabs/eksdemo"
  version "0.18.0"
  license "MIT-0"

  depends_on "weaveworks/tap/eksctl"

  on_macos do
    on_intel do
      url "https://github.com/awslabs/eksdemo/releases/download/v0.18.0/eksdemo_Darwin_x86_64.tar.gz"
      sha256 "ed173638804cdf0be36ec8ca6849eea12c48e354f50cb44a5266c64cc431592e"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
    on_arm do
      url "https://github.com/awslabs/eksdemo/releases/download/v0.18.0/eksdemo_Darwin_arm64.tar.gz"
      sha256 "263c0f0fe742dba00aa801040d570fd213c4894946c83733e8bedd106d7369a1"

      def install
        bin.install "eksdemo"
        bash_completion.install "completions/eksdemo.bash" => "eksdemo"
        zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
        fish_completion.install "completions/eksdemo.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/awslabs/eksdemo/releases/download/v0.18.0/eksdemo_Linux_x86_64.tar.gz"
        sha256 "ee2c4407722a72e2cc958a4ffb6e3d26d5a832fc9945896c405f5d6d9edcf41c"

        def install
          bin.install "eksdemo"
          bash_completion.install "completions/eksdemo.bash" => "eksdemo"
          zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
          fish_completion.install "completions/eksdemo.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/awslabs/eksdemo/releases/download/v0.18.0/eksdemo_Linux_arm64.tar.gz"
        sha256 "7058d4df2540c2295728f86ede07e4b4cdbf1ac2cf32dd14417ec4c619f75195"

        def install
          bin.install "eksdemo"
          bash_completion.install "completions/eksdemo.bash" => "eksdemo"
          zsh_completion.install "completions/eksdemo.zsh" => "_eksdemo"
          fish_completion.install "completions/eksdemo.fish"
        end
      end
    end
  end
end
