name: Update eksctl Formula

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  update-eksctl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if eksctl update issue
        id: check_issue
        run: |
          if [[ "${{ github.event.issue.title }}" =~ ^Update\ eksctl\ to\ v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "is_eksctl_update=true" >> $GITHUB_OUTPUT
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "is_eksctl_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Get latest eksctl release
        if: steps.check_issue.outputs.is_eksctl_update == 'true'
        id: latest
        run: |
          echo "version=${{ steps.check_issue.outputs.version }}" >> $GITHUB_OUTPUT
          echo "tag=v${{ steps.check_issue.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Check if update needed
        if: steps.check_issue.outputs.is_eksctl_update == 'true'
        id: check
        run: |
          CURRENT=$(grep 'version "' Formula/eksctl.rb | sed 's/.*version "\(.*\)".*/\1/')
          if [ "$CURRENT" != "${{ steps.latest.outputs.version }}" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Download and get SHA256 hashes
        if: steps.check.outputs.update_needed == 'true'
        id: hashes
        run: |
          VERSION=${{ steps.latest.outputs.version }}
          BASE_URL="https://github.com/eksctl-io/eksctl/releases/download/v${VERSION}"
          
          # Download and get SHA256 for each platform
          echo "darwin_arm64=$(curl -sL "${BASE_URL}/eksctl_Darwin_arm64.tar.gz" | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "darwin_amd64=$(curl -sL "${BASE_URL}/eksctl_Darwin_amd64.tar.gz" | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "linux_amd64=$(curl -sL "${BASE_URL}/eksctl_Linux_amd64.tar.gz" | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "linux_arm64=$(curl -sL "${BASE_URL}/eksctl_Linux_arm64.tar.gz" | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "linux_armv6=$(curl -sL "${BASE_URL}/eksctl_Linux_armv6.tar.gz" | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Update formula
        if: steps.check.outputs.update_needed == 'true'
        run: |
          VERSION=${{ steps.latest.outputs.version }}
          
          # Update version
          sed -i "s/version \".*\"/version \"${VERSION}\"/" Formula/eksctl.rb
          
          # Update URLs and SHA256 hashes
          sed -i "s|releases/download/v[^/]*/|releases/download/v${VERSION}/|g" Formula/eksctl.rb
          sed -i "/eksctl_Darwin_arm64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${{ steps.hashes.outputs.darwin_arm64 }}\"/" Formula/eksctl.rb
          sed -i "/eksctl_Darwin_amd64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${{ steps.hashes.outputs.darwin_amd64 }}\"/" Formula/eksctl.rb
          sed -i "/eksctl_Linux_amd64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${{ steps.hashes.outputs.linux_amd64 }}\"/" Formula/eksctl.rb
          sed -i "/eksctl_Linux_arm64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${{ steps.hashes.outputs.linux_arm64 }}\"/" Formula/eksctl.rb
          sed -i "/eksctl_Linux_armv6.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"${{ steps.hashes.outputs.linux_armv6 }}\"/" Formula/eksctl.rb

      - name: Create Pull Request
        if: steps.check.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update eksctl to v${{ steps.latest.outputs.version }}"
          title: "Update eksctl to v${{ steps.latest.outputs.version }}"
          body: |
            Automated update of eksctl formula to version ${{ steps.latest.outputs.version }}.
            
            Changes:
            - Updated version to ${{ steps.latest.outputs.version }}
            - Updated download URLs
            - Updated SHA256 hashes for all platforms
          branch: update-eksctl-${{ steps.latest.outputs.version }}
          delete-branch: true

      - name: Close issue
        if: steps.check.outputs.update_needed == 'true'
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state":"closed"}' \
            && curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"Update PR created automatically."}'